#game setup
WIDTH = 500
HEIGHT = 500
FPS = 60

#player settings
PLAYER_START_X = 250
PLAYER_START_Y = 350
PLAYER_SIZE = 0.25
PLAYER_SPEED = 8
GUN_OFFSET_X = 45
GUN_OFFSET_Y = 20

#pgun settings
PGUN_START_X = PLAYER_START_X
PGUN_START_Y = PLAYER_START_Y
PGUN_SIZE = 0.20

#bullet settings
SHOOT_COOLDOWN = 45
BULLET_SCALE = 0.4
BULLET_SPEED = 20
BULLET_LIFETIME = 750
