#game setup
WIDTH = 500
HEIGHT = 500
FPS = 60

#player settings
PLAYER_START_X = 250
PLAYER_START_Y = 450
PLAYER_SIZE = 0.25
PLAYER_SPEED = 8
GUN_OFFSET_X = 0
GUN_OFFSET_Y = 0

#pgun settings
PGUN_START_X = PLAYER_START_X
PGUN_START_Y = PLAYER_START_Y
PGUN_SIZE = 0.15

#bullet settings
SHOOT_COOLDOWN = 45
BULLET_SCALE = 0.2
BULLET_SPEED = 40
BULLET_LIFETIME = 750

#portal settings
PORTAL_SCALE = 0.2
SPAWNED_PORTALS = 0
PORTAL_COOLDOWN = 8
MAX_PORTALS = 2